rm -rf d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/
             mkdir d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin
              
            ln -fs d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/* d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/ 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/404.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/archive.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/css/admin/customizer.css d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/css/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/css/admin/edit-page.css d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/css/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/css/admin/group_panel_widget.css d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/css/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/fontawesome/fontawesome-webfont.eot d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/fontawesome 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/fontawesome/fontawesome-webfont.otf d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/fontawesome 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/fontawesome/fontawesome-webfont.ttf d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/fontawesome 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/fontawesome/FontAwesome.otf d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/fontawesome 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/hanken/hanken-book-webfont.eot d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/hanken 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/hanken/hanken-book-webfont.ttf d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/hanken 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/hanken/hanken-light-webfont.eot d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/hanken 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/hanken/hanken-light-webfont.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/hanken 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/hanken/hanken-light-webfont.ttf d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/hanken 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/noto-sans/noto-sans-v6-latin-regular.eot d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/noto-sans 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/noto-sans/noto-sans-v6-latin-regular.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/noto-sans 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/noto-sans/noto-sans-v6-latin-regular.ttf d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/noto-sans 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/open-sans/open-sans-v14-latin-regular.eot d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/open-sans 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/open-sans/open-sans-v14-latin-regular.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/open-sans 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/open-sans/open-sans-v14-latin-regular.ttf d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/open-sans 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/roboto/roboto-v16-latin-regular.eot d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/roboto 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/roboto/roboto-v16-latin-regular.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/roboto 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/roboto/roboto-v16-latin-regular.ttf d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/roboto 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/emerald.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/light.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/outdoors.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/Pattern.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/pencil.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/pirates.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/satellite.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/select-arrow.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/select-arrows.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/streets-basic.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/streets.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/admin-general.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/admin-general.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/customizer_preview.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/customizer_preview.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/customizer.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/customizer.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/edit-nav-menus.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/edit-nav-menus.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/edit-page.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/edit-page.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/group_panel_widget.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/group_panel_widget.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/admin-general.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/admin-general.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/customizer_preview.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/customizer_preview.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/customizer.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/customizer.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/edit-nav-menus.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/edit-nav-menus.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/edit-page.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/edit-page.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/group_panel_widget.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/group_panel_widget.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/custom-elements.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/main.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/main.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/system.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/systemjs/main.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/systemjs/main.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/systemjs/test.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/systemjs/test.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/systemjs/test1.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/systemjs/test1.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/test.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/test.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/test1.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/test1.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/3-layers.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/add-to-favorites-icon-svg.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/addphoto.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/arrow-curved.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/arrow-right.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/arrow.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/cards.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/carousel-arrow-svg.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/checked-icon-small.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/checked-icon.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/close-icon-svg.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/filter-dark.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/filter.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/findme-dark.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/findme.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/heart-svg.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/loader-svg.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/map-pin-cluster-svg.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/map-pin-empty-svg.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/map-pin-selected-svg.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/map-pin-svg.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/map.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/menu-bars-svg.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/pin-simple-svg.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/search-icon-mobile-svg.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/search-icon-svg.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/share-icon-svg.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/write-a-review-icon-svg.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/category.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/comments.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/editor-style.css d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/footer.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/functions.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/header.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/activation.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/config.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/custom-header.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/customizer.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/extras.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/demo-data/demo_data.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import/demo-data 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/demo-data/demo_data.xml d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import/demo-data 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/demo-data/listing_categories.xml d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import/demo-data 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/demo-data/listing_tags.xml d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import/demo-data 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/import-demo-listing-categories.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/import-demo-listing-tags.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/import-demo-posts-pages.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/import-demo-theme-options.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/import-demo-widgets.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/wordpress-importer/parsers.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import/wordpress-importer 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/wordpress-importer/wordpress-importer.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import/wordpress-importer 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/wordpress-importer/wpgrade-import-class.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import/wordpress-importer 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/integrations.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/integrations/jetpack.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/integrations 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/integrations/jetpack/responsive-videos.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/integrations/jetpack 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/integrations/jetpack/responsive-videos/responsive-videos.css d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/integrations/jetpack/responsive-videos 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/integrations/jetpack/responsive-videos/responsive-videos.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/integrations/jetpack/responsive-videos 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/integrations/jetpack/responsive-videos/responsive-videos.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/integrations/jetpack/responsive-videos 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/integrations/jetpack/responsive-videos/systemjs/responsive-videos.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/integrations/jetpack/responsive-videos/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/integrations/jetpack/responsive-videos/systemjs/responsive-videos.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/integrations/jetpack/responsive-videos/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/integrations/wpml.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/integrations 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/integrations/yoast-seo.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/integrations 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/required-plugins/class-tgm-plugin-activation.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/required-plugins 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/required-plugins/required-plugins.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/required-plugins 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/template-tags.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/widgets.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/index.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/page-templates/front_page.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/page-templates 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/page-templates/full_width_no_title.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/page-templates 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/page-templates/full_width.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/page-templates 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/page.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/rtl.css d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/screenshot.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/search.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/searchform.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/sidebar.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/single.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/style.css d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/style1.css d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/tag.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/template-parts/content-hero.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/template-parts 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/template-parts/content-none.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/template-parts 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/template-parts/content-page.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/template-parts 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/template-parts/content-search.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/template-parts 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/template-parts/content-single.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/template-parts 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/template-parts/content.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/template-parts 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/template-parts/header-fields.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/template-parts 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/wpml-config.xml d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
