rm -rf d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/
             mkdir d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin
              
            ln -fs d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/* d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/ 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/404.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/archive.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/css/admin/customizer.css d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/css/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/css/admin/edit-page.css d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/css/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/css/admin/group_panel_widget.css d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/css/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/fontawesome/fontawesome-webfont.eot d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/fontawesome 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/fontawesome/fontawesome-webfont.otf d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/fontawesome 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/fontawesome/fontawesome-webfont.ttf d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/fontawesome 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/fontawesome/FontAwesome.otf d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/fontawesome 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/hanken/hanken-book-webfont.eot d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/hanken 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/hanken/hanken-book-webfont.ttf d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/hanken 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/hanken/hanken-light-webfont.eot d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/hanken 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/hanken/hanken-light-webfont.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/hanken 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/hanken/hanken-light-webfont.ttf d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/hanken 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/hanken/OFL-FAQ.txt d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/hanken 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/noto-sans/noto-sans-v6-latin-regular.eot d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/noto-sans 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/noto-sans/noto-sans-v6-latin-regular.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/noto-sans 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/noto-sans/noto-sans-v6-latin-regular.ttf d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/noto-sans 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/open-sans/open-sans-v14-latin-regular.eot d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/open-sans 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/open-sans/open-sans-v14-latin-regular.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/open-sans 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/open-sans/open-sans-v14-latin-regular.ttf d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/open-sans 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/roboto/roboto-v16-latin-regular.eot d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/roboto 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/roboto/roboto-v16-latin-regular.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/roboto 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/fonts/roboto/roboto-v16-latin-regular.ttf d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/fonts/roboto 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/list.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/pattern.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/select-arrow.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/sidebar_left.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/sidebar_none.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/sidebar_right.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/tile.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/vc/bitcoin_blog.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img/vc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/vc/bitcoin_container.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img/vc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/vc/bitcoin_counter.jpg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img/vc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/vc/bitcoin_counter.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img/vc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/vc/bitcoin_item_container.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img/vc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/vc/bitcoin_plot.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img/vc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/vc/bitcoin_testimonials.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img/vc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/vc/blue_btn.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img/vc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/vc/photo5409300555723024491.jpg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img/vc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/vc/theme_button.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img/vc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/img/vc/white_btn.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/img/vc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/admin-general.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/admin-general.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/customizer_preview.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/customizer_preview.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/customizer.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/customizer.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/edit-nav-menus.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/edit-nav-menus.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/edit-page.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/edit-page.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/group_panel_widget.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/group_panel_widget.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/admin-general.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/admin-general.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/customizer_preview.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/customizer_preview.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/customizer.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/customizer.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/edit-nav-menus.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/edit-nav-menus.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/edit-page.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/edit-page.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/group_panel_widget.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/admin/systemjs/group_panel_widget.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/admin/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/calc.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/custom-elements.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/main.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/main.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/system.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/systemjs/main.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/systemjs/main.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/systemjs/test.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/systemjs/test.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/systemjs/test1.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/systemjs/test1.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/test.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/test.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/test1.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/js/test1.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/js 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/checked-icon.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/close-icon-svg.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/comment-icon.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/fb-icon.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/fb-icon.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/goog-icon.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/goog-icon.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/heart-svg.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/likes-icon.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/menu-bars-svg.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/pntr-icon.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/pntr-icon.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/shape.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/shape.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/star.000.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/star.1.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/star.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/star.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/tw-icon.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/assets/svg/tw-icon.svg d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/assets/svg 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/category.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/comments.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/editor-style.css d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/footer.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/functions.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/header.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/activation.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/config.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/custom-header.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/customizer.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/extras.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/demo-data/demo_data.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import/demo-data 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/demo-data/demo_data.xml d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import/demo-data 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/import-demo-listing-categories.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/import-demo-listing-tags.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/import-demo-posts-pages.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/import-demo-theme-options.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/import-demo-widgets.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/wordpress-importer/parsers.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import/wordpress-importer 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/wordpress-importer/wordpress-importer.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import/wordpress-importer 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/import/wordpress-importer/wpgrade-import-class.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/import/wordpress-importer 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/integrations.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/integrations/jetpack.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/integrations 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/integrations/jetpack/responsive-videos.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/integrations/jetpack 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/integrations/jetpack/responsive-videos/responsive-videos.css d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/integrations/jetpack/responsive-videos 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/integrations/jetpack/responsive-videos/responsive-videos.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/integrations/jetpack/responsive-videos 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/integrations/jetpack/responsive-videos/responsive-videos.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/integrations/jetpack/responsive-videos 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/integrations/jetpack/responsive-videos/systemjs/responsive-videos.js d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/integrations/jetpack/responsive-videos/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/integrations/jetpack/responsive-videos/systemjs/responsive-videos.js.map d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/integrations/jetpack/responsive-videos/systemjs 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/integrations/wpml.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/integrations 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/integrations/yoast-seo.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/integrations 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/required-plugins/class-tgm-plugin-activation.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/required-plugins 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/required-plugins/languages/tgmpa.pot d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/required-plugins/languages 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/required-plugins/LICENSE.md d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/required-plugins 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/required-plugins/required-plugins.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/required-plugins 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/required-plugins/visual-composer/js_composer.zip d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/required-plugins/visual-composer 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/required-plugins/visual-composer/Licensing/GPL.txt d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/required-plugins/visual-composer/Licensing 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/required-plugins/visual-composer/Licensing/README_License.txt d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/required-plugins/visual-composer/Licensing 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/required-plugins/visual-composer/README_FIRST.html d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/required-plugins/visual-composer 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/required-plugins/visual-composer/README-FIRST.html d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/required-plugins/visual-composer 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/cv_bitcoin_testimonials.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/extend_vc.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/init.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/params/vc_forit_datepicker.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes/params 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/params/vc_helptext.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes/params 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/params/vc_layout_select.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes/params 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/params/vc_offset_box.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes/params 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/params/vc_pick_the_post.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes/params 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/params/vc_range.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes/params 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/params/vc_responsive_param.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes/params 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/params/vc_social_share.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes/params 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/vc_bitcoin_blog.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/vc_bitcoin_calc.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/vc_bitcoin_container.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/vc_bitcoin_counter.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/vc_bitcoin_plot.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/vc_bitcoin_testimonials.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/vc_bitcoin_testomonials.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/vc_theme_btn.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/vс_bitcoin_testimonial.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/vс_bitcoin_testimonials.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/shortcodes/vс_bitcoin_testimonialss.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc/shortcodes 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/template-tags.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/inc/widgets.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/inc 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/index.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/languages/bitcoin.pot d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/languages 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/languages/readme.txt d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/languages 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/page-templates/front_page.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/page-templates 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/page.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/rtl.css d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/screenshot.png d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/search.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/sidebar.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/single.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/slider.css d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/style.css d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/styles/theme.css d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/styles 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/tag.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/template-parts/content-hero.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/template-parts 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/template-parts/content-none.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/template-parts 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/template-parts/content-page.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/template-parts 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/template-parts/content-single.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/template-parts 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/template-parts/content.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/template-parts 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/template-parts/related-posts.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/template-parts 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/template-parts/relative.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/template-parts 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/template-parts/social-share.php d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/template-parts 
ln -f d:/OpenServer/domains/wordpress/wp-content/startwp/dist/theme/wpml-config.xml d:/OpenServer/domains/wordpress/wp-content/themes/bitcoin/. 
