rm -rf d:/OSPanel/domains/wp/wp-content/themes/bitstarter/
             mkdir d:/OSPanel/domains/wp/wp-content/themes/bitstarter
              
            ln -fs d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/* d:/OSPanel/domains/wp/wp-content/themes/bitstarter/ 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/404.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/. 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/archive.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/. 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/css/admin/customizer.css d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/css/admin 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/css/admin/edit-page.css d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/css/admin 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/css/bundle.css d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/css 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/fonts/fontawesome/fontawesome-webfont.eot d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/fonts/fontawesome 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/fonts/fontawesome/fontawesome-webfont.otf d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/fonts/fontawesome 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/fonts/fontawesome/fontawesome-webfont.ttf d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/fonts/fontawesome 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/fonts/hanken/hanken-book-webfont.eot d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/fonts/hanken 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/fonts/hanken/hanken-book-webfont.ttf d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/fonts/hanken 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/fonts/hanken/hanken-light-webfont.eot d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/fonts/hanken 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/fonts/hanken/hanken-light-webfont.svg d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/fonts/hanken 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/fonts/hanken/hanken-light-webfont.ttf d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/fonts/hanken 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/fonts/hanken/OFL-FAQ.txt d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/fonts/hanken 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/fonts/noto-sans/noto-sans-v6-latin-regular.eot d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/fonts/noto-sans 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/fonts/noto-sans/noto-sans-v6-latin-regular.svg d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/fonts/noto-sans 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/fonts/noto-sans/noto-sans-v6-latin-regular.ttf d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/fonts/noto-sans 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/fonts/open-sans/open-sans-v14-latin-regular.eot d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/fonts/open-sans 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/fonts/open-sans/open-sans-v14-latin-regular.svg d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/fonts/open-sans 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/fonts/open-sans/open-sans-v14-latin-regular.ttf d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/fonts/open-sans 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/fonts/roboto/roboto-v16-latin-regular.eot d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/fonts/roboto 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/fonts/roboto/roboto-v16-latin-regular.svg d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/fonts/roboto 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/fonts/roboto/roboto-v16-latin-regular.ttf d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/fonts/roboto 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/list.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/pattern.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/select-arrow.svg d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/sidebar_left.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/sidebar_none.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/sidebar_right.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/tile.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/vc/bitstarter_blog.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img/vc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/vc/bitstarter_card.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img/vc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/vc/bitstarter_container.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img/vc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/vc/bitstarter_counter.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img/vc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/vc/bitstarter_counterdown.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img/vc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/vc/bitstarter_crypto_calculator.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img/vc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/vc/bitstarter_distribution.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img/vc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/vc/bitstarter_item_container.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img/vc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/vc/bitstarter_mark.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img/vc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/vc/bitstarter_plot.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img/vc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/vc/bitstarter_team.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img/vc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/vc/bitstarter_testimonials.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img/vc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/vc/blue_btn.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img/vc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/vc/theme_button.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img/vc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/img/vc/white_btn.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/img/vc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/js/admin/admin-general.js d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/js/admin 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/js/admin/customizer_preview.js d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/js/admin 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/js/admin/customizer.js d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/js/admin 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/js/admin/edit-page.js d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/js/admin 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/js/calc.js d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/js 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/js/expand.js d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/js 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/js/fallbacks/CSSPlugin.min.js d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/js/fallbacks 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/js/fallbacks/Highcharts.min.js d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/js/fallbacks 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/js/fallbacks/imagesLoaded.min.js d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/js/fallbacks 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/js/fallbacks/jquery.mousewheel.min.js d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/js/fallbacks 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/js/fallbacks/scroll-to-plugin.min.js d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/js/fallbacks 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/js/fallbacks/slick.min.js d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/js/fallbacks 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/js/fallbacks/tween-max.min.js d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/js/fallbacks 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/js/main.js d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/js 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/js/polyfill.js d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/js 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/js/system.js d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/js 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/svg/close-icon-svg.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/svg 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/svg/comment-icon.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/svg 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/svg/common.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/svg 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/svg/fb-icon.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/svg 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/svg/goog-icon.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/svg 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/svg/heart-svg.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/svg 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/svg/likes-icon.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/svg 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/svg/menu-bars-svg.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/svg 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/svg/pntr-icon.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/svg 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/svg/sc-team-fb.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/svg 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/svg/sc-team-in.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/svg 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/svg/sc-team-tw.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/svg 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/svg/social-dis.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/svg 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/svg/social-fb.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/svg 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/svg/social-git.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/svg 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/svg/social-ig.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/svg 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/svg/social-in.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/svg 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/svg/social-tel.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/svg 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/svg/social-tw.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/svg 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/svg/star.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/svg 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/assets/svg/tw-icon.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/assets/svg 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/category.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/. 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/comments.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/. 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/editor-style.css d:/OSPanel/domains/wp/wp-content/themes/bitstarter/. 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/footer.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/. 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/functions.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/. 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/header.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/. 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/activation.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/config.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/custom-header.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/customizer.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/extras.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/integrations.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/integrations/jetpack.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/integrations 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/integrations/jetpack/responsive-videos.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/integrations/jetpack 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/integrations/jetpack/responsive-videos/responsive-videos.css d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/integrations/jetpack/responsive-videos 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/integrations/jetpack/responsive-videos/responsive-videos.js d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/integrations/jetpack/responsive-videos 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/integrations/jetpack/responsive-videos/responsive-videos.min.js d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/integrations/jetpack/responsive-videos 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/integrations/timeline-express.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/integrations 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/required-plugins/bitstarter-plugin/bitstarter-core.zip d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/required-plugins/bitstarter-plugin 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/required-plugins/class-tgm-plugin-activation.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/required-plugins 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/required-plugins/languages/bitstarter.pot d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/required-plugins/languages 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/required-plugins/LICENSE.md d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/required-plugins 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/required-plugins/required-plugins.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/required-plugins 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/required-plugins/visual-composer/js_composer.zip d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/required-plugins/visual-composer 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/required-plugins/visual-composer/Licensing/GPL.txt d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/required-plugins/visual-composer/Licensing 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/required-plugins/visual-composer/Licensing/README_License.txt d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/required-plugins/visual-composer/Licensing 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/required-plugins/visual-composer/README-FIRST.html d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/required-plugins/visual-composer 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/shortcodes/extend_vc.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/shortcodes 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/shortcodes/init.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/shortcodes 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/shortcodes/params/vc_helptext.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/shortcodes/params 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/shortcodes/vc_bitstarter_blog.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/shortcodes 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/shortcodes/vc_bitstarter_calc.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/shortcodes 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/shortcodes/vc_bitstarter_card.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/shortcodes 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/shortcodes/vc_bitstarter_container.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/shortcodes 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/shortcodes/vc_bitstarter_counter.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/shortcodes 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/shortcodes/vc_bitstarter_counterdown.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/shortcodes 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/shortcodes/vc_bitstarter_distribution.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/shortcodes 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/shortcodes/vc_bitstarter_mark.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/shortcodes 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/shortcodes/vc_bitstarter_plot.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/shortcodes 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/shortcodes/vc_bitstarter_team.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/shortcodes 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/shortcodes/vc_bitstarter_testimonials.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc/shortcodes 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/template-tags.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/inc/widgets.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/inc 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/index.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/. 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/languages/bitstarter.pot d:/OSPanel/domains/wp/wp-content/themes/bitstarter/languages 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/languages/readme.txt d:/OSPanel/domains/wp/wp-content/themes/bitstarter/languages 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/page-templates/front_page.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/page-templates 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/page.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/. 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/rtl.css d:/OSPanel/domains/wp/wp-content/themes/bitstarter/. 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/screenshot.png d:/OSPanel/domains/wp/wp-content/themes/bitstarter/. 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/search.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/. 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/sidebar.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/. 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/single.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/. 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/style.css d:/OSPanel/domains/wp/wp-content/themes/bitstarter/. 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/styles/theme.css d:/OSPanel/domains/wp/wp-content/themes/bitstarter/styles 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/tag.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/. 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/template-parts/content-hero.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/template-parts 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/template-parts/content-none.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/template-parts 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/template-parts/content-page.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/template-parts 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/template-parts/content-single.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/template-parts 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/template-parts/content.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/template-parts 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/template-parts/related-posts.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/template-parts 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/template-parts/social-share.php d:/OSPanel/domains/wp/wp-content/themes/bitstarter/template-parts 
ln -f d:/OSPanel/domains/wp/wp-content/startwp/dist/theme/wpml-config.xml d:/OSPanel/domains/wp/wp-content/themes/bitstarter/. 
